name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    # self-hosted 러너를 사용합니다.
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Ruby using ruby-build
        run: |
          # 원하는 Ruby 버전 설정
          RUBY_VERSION=3.1.4
          # 설치 경로를 지정합니다. (예: /opt/hostedtoolcache/Ruby/3.1.4/x64)
          INSTALL_DIR=/opt/hostedtoolcache/Ruby/$RUBY_VERSION/x64
          # Ruby가 설치되어 있지 않으면 설치 진행
          if [ ! -d "$INSTALL_DIR" ]; then
            echo "Installing Ruby $RUBY_VERSION..."
            sudo ruby-build $RUBY_VERSION $INSTALL_DIR
            sudo touch $INSTALL_DIR.complete
          else
            echo "Ruby $RUBY_VERSION is already installed."
          fi
          # PATH에 설치된 Ruby의 bin 디렉토리 추가
          export PATH="$INSTALL_DIR/bin:$PATH"
          ruby -v

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --trace --verbose
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
